package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;

import java.net.URL;
import java.util.Date;
import java.util.ResourceBundle;
import java.util.Timer;
import java.util.TimerTask;

import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.stage.Stage;

public class BadySeptController implements Initializable {
	@FXML
	private Label lable1;

	int min = 2;

	long start = System.currentTimeMillis();

	final long end = start + min * 60 * 1000;
	final Timer timer = new Timer();

	public void initialize(URL location, ResourceBundle resources) {

		//lable1.setText("rest time : ");
		timer.schedule(new TimerTask() {
			public void run() {
				long show = end - System.currentTimeMillis();
				long m = show / 1000 / 60 % 60;
				long s = show / 1000 % 60;
				// System.out.println("现在时间："+h+"时"+m+"分"+s+"秒");
				Platform.runLater(new Runnable() {
					public void run() {
						lable1.setText(String.valueOf(m) + ":" + String.valueOf(s));
						// lblTimer.setText(downloadTimer.getTime());
					}
				});
			}
		}, 0, 1000);
		timer.schedule(new TimerTask() {
			public void run() {
				timer.cancel();
				//clear();
			}
		}, new Date(end));
	}
	// Event Listener on Button.onAction
	@FXML
	public void Back(ActionEvent event) {
		// TODO Autogenerated
		try {
			((Node) event.getSource()).getScene().getWindow().hide();
			Stage primaryStage = new Stage();
			Parent root = FXMLLoader.load(getClass().getResource("/application/MainWindows.fxml"));
			Scene scene = new Scene(root);
			scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			primaryStage.setScene(scene);
			primaryStage.setTitle("Red");
			primaryStage.show();
		} catch (Exception e) {

		}
	}
}
